const ActionType = {
	LOAD_MESSAGES: "LOAD_MESSAGES",
	ADD_MESSAGE: "ADD_MESSAGE",
	DELETE_MESSAGE: "DELETE_MESSAGE",
	EDIT_MESSAGE: "UPDATE_MESSAGE",
}

const UserActionType = {
	LOAD_USERS: "LOAD_USERS",
	ADD_USER: "ADD_USER",
	DELETE_USER: "DELETE_USER",
	EDIT_USER: "EDIT_USER",
}

export { ActionType, UserActionType };